server:
    mode: "test"
    port: ":11009" # best 1024 up

redis:
    db: 0 # defaults 0
    failover: false
    password: ""
    # master_name: "" # should enable when failover = true
    addrs:
        - "127.0.0.1:6379"
    size: 10
    network: "tcp"

session:
    max_age: 604800

acc:
    host: "http://10.200.20.25:9100"
    username: "root"
    password: "root"
sso:
    host: "http://sso-dev.qiniu.io"
    client_id: "0ur4QrAWvy0flZS9D8cbAOa9zYd4xW8OklU0WB4rRGx8nSlUf1EG8XLZ3FZRRRXa2XS7ZUd1QfHl8EcQQVysMu7WyNRBKSqqRGqOM8fa2GMVRhiS5mziG5BDZPOpUI29"
    cookie_secret: "YT9hu3ILHgcoSYTg42FBInYtojLxQhkv1Mnc0CuIKLtRu58FQxYHbRRt1jea414a"
