server:
    mode: "test"
    port: ":11009" # best 1024 up

auth:
    mock_token: true
    secret_key: ""
    token_expires_in: 7*24*3600

redis:
    db: 0 # defaults 0
    failover: false
    password: ""
    # master_name: "" # should enable when failover = true
    addrs:
        - "127.0.0.1:6379"
    size: 10
    network: "tcp"

session:
    max_age: 604800

services:
    gaea_host: "http://bo-gaea-admin-koderover-staging-bo.cs-spock.cloudappl.com"
acc:
    host: "http://10.200.20.25:9100"
    username: "root"
    password: "root"
    client_id: "xxx"
    client_secret: "xxx"
sso:
    host: "https://sso-dev.qiniu.io"
    client_id: "1YlkJR3sYw7zpBMSTNCesc9O9ViF9tCO03JDXZOGBpxkQ36QuIag2PAvPXdP35rCF2DMvMkIIXZBD1EBHzPBYZt1wJlK35YdIM9TkVagOaybfocuqSNOV6hK64offScqv"
    client_secret: "lzzexEXo49nFOdWXbhMEyAuTwX88pHCWMupFpWeZZvpZlxPBO1w0STqguVAM62TXzJugH3T59qREm6te1uz2juHu3ycbLhLJJHnnQMLvi1Di0k8538Hi3sm59CdL6bo7h"
    cookie_secret: ""
