# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 672a764aa6898cb94ebe8a4cde2580ed772fe62d75839d70c046a3bd5f63fe69b8a4883f7131cc702ef870f57ae3d61b8e239117e65fdbfba96811b9820812c3
  sso:
    cookie_secret: YT9hu3ILHgcoSYTg42FBInYtojLxQhkv1Mnc0CuIKLtRu58FQxYHbRRt1jea414a
    client_id: 0ur4QrAWvy0flZS9D8cbAOa9zYd4xW8OklU0WB4rRGx8nSlUf1EG8XLZ3FZRRRXa2XS7ZUd1QfHl8EcQQVysMu7WyNRBKSqqRGqOM8fa2GMVRhiS5mziG5BDZPOpUI29
    client_secret: 8MKUKwavxvhtPgYSojMUTitU5hn6acacU9hTTB3c12ce33FUxHt9L96Gcxmo22cQlogDWp3txo6kA0WHaGPhd1xaxDgTCvW5X0l7paca0nyAlWASZYm1BKKi7yA5ooKU
  admin:
    username: root
    password: root

test:
  secret_key_base: dcd39cf796db4f2953b8cf439469c3246bb4becb74cf1119d7fb3597252783ab49b87970b3fab98263334eca2b4f75f16dbb4277eac1d43d11fbbeec443a8801

dev_env:
  secret_key_base: f6ff1349ee05320c057313f290d9684c4266f2281e340f3441883487924642104ae9c7a93043bad6be4965893f45320a4d0ef623f6939c86a3039ae08aa2537a
  sso:
    cookie_secret: YT9hu3ILHgcoSYTg42FBInYtojLxQhkv1Mnc0CuIKLtRu58FQxYHbRRt1jea414a
    client_id: 0ur4QrAWvy0flZS9D8cbAOa9zYd4xW8OklU0WB4rRGx8nSlUf1EG8XLZ3FZRRRXa2XS7ZUd1QfHl8EcQQVysMu7WyNRBKSqqRGqOM8fa2GMVRhiS5mziG5BDZPOpUI29
    client_secret: 8MKUKwavxvhtPgYSojMUTitU5hn6acacU9hTTB3c12ce33FUxHt9L96Gcxmo22cQlogDWp3txo6kA0WHaGPhd1xaxDgTCvW5X0l7paca0nyAlWASZYm1BKKi7yA5ooKU
  admin:
    username: root
    password: root

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c057313f290d934879281e340f344188d6be49658ba684c4266f2939c86a93f45320a4d0ef623f624642104ae9c7a930433039ae08aa2537af6ff1349ee05320
  sso:
    cookie_secret: YT9hu3ILHgcoSYTg42FBInYtojLxQhkv1Mnc0CuIKLtRu58FQxYHbRRt1jea414a
    client_id: 0ur4QrAWvy0flZS9D8cbAOa9zYd4xW8OklU0WB4rRGx8nSlUf1EG8XLZ3FZRRRXa2XS7ZUd1QfHl8EcQQVysMu7WyNRBKSqqRGqOM8fa2GMVRhiS5mziG5BDZPOpUI29
    client_secret: 8MKUKwavxvhtPgYSojMUTitU5hn6acacU9hTTB3c12ce33FUxHt9L96Gcxmo22cQlogDWp3txo6kA0WHaGPhd1xaxDgTCvW5X0l7paca0nyAlWASZYm1BKKi7yA5ooKU 
  admin:
    username: root
    password: root